import type {Metadata} from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Outfit({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Mirelan&co",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>

        {children}


        </body>
        </html>
    );
}
